import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export const dynamic='force-dynamic';
const fail=(error:string,status:number)=>Response.json({error},{status,headers:{'Cache-Control':'no-store'}});
async function key(owner:string,id:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(owner));const ns=Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');return `logos/${ns}/${id}`;}
function imageType(b:Uint8Array){if([137,80,78,71,13,10,26,10].every((v,i)=>b[i]===v))return 'image/png';if(b[0]===255&&b[1]===216&&b[2]===255)return 'image/jpeg';if(String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP')return 'image/webp';return null;}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return fail('Inicia sessão para carregar o logótipo.',401);
 if(request.headers.get('sec-fetch-site')==='cross-site'||(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin))return fail('Origem não permitida.',403);
 if(Number(request.headers.get('content-length'))>300000)return fail('O logótipo deve ter no máximo 256 KB.',413);
 try{const form=await request.formData();const file=form.get('logo');if(!(file instanceof File)||file.size>262144||file.size<12)return fail('Envia uma imagem PNG, JPEG ou WebP até 256 KB.',400);const bytes=new Uint8Array(await file.arrayBuffer());const type=imageType(bytes);if(!type)return fail('Formato não suportado. Usa PNG, JPEG ou WebP.',400);if(!env.BUCKET)return fail('O carregamento está temporariamente indisponível.',503);const id=crypto.randomUUID();await env.BUCKET.put(await key(user.userId,id),bytes,{httpMetadata:{contentType:type}});return Response.json({id},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error('logo upload failed',e);return fail('Não foi possível carregar o logótipo.',503);}}
export async function GET(request:Request){const user=await getChatGPTUser();if(!user)return fail('Sessão necessária.',401);const id=new URL(request.url).searchParams.get('id');if(!id||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id))return fail('Logótipo inválido.',400);try{const object=await env.BUCKET?.get(await key(user.userId,id));if(!object)return fail('Logótipo não encontrado.',404);return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'private, max-age=300','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'"}});}catch{return fail('Não foi possível abrir o logótipo.',503);}}
