'use client';
import {useState} from 'react';
import {Camera,Wallet,TrendingUp,Euro,Save} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {commercialSummary,licenseStatus} from '@/lib/commercial';
import type {Records} from '@/lib/model';
const eur=(n:number)=>n.toLocaleString('pt-PT',{style:'currency',currency:'EUR'});
export default function CommercialPanel({data,save,saving,scope,readOnly,onEdit,initialId=''}:{initialId?:string;data:Records;save:(d:Records)=>Promise<boolean>;saving:boolean;scope:string;readOnly:boolean;onEdit:(id:string)=>void}){
 const [selected,setSelected]=useState(initialId),[draft,setDraft]=useState<Record<string,string>>({}),[dirty,setDirty]=useState(false);
 const r=data.resellers.find(r=>r.id===(readOnly?scope:selected));const m=r?commercialSummary(data,r):null;
 function choose(id:string){setSelected(id);setDraft({});setDirty(false)}
 const priceValue=(id:string)=>Object.hasOwn(draft,id)?draft[id]:r?.salePrices[id]?.toString()??'';
 async function persist(){if(!r)return;const prices={...r.salePrices};for(const [id,value]of Object.entries(draft)){if(value==='')delete prices[id];else prices[id]=Number(value)}if(await save({...data,resellers:data.resellers.map(x=>x.id===r.id?{...x,salePrices:prices}:x)})){setDraft({});setDirty(false)}}
 return <><section className="panel form-panel commercial-picker"><div><h2>Carteira e preços de revenda</h2><p>Os valores são mensais, sem IVA, e representam uma previsão comercial.</p></div>{!readOnly&&<div><Label>Revendedor</Label><Select value={selected||'none'} onValueChange={choose} disabled={dirty||saving}><SelectTrigger aria-label="Revendedor da carteira"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Selecionar revendedor</SelectItem>{data.resellers.map(r=><SelectItem value={r.id} key={r.id}>{r.name}</SelectItem>)}</SelectContent></Select></div>}</section>
 {!r||!m?<section className="panel empty"><Wallet className="mx-auto mb-5"/><h2>Seleciona um revendedor</h2><p>Consulta a capacidade contratada e configura os preços de venda de cada plano.</p></section>:<>
 <section className="metrics commercial-metrics">{[['Carteira de câmaras',`${m.all.length} / ${m.limit??'—'}`,m.limit===null?'Sem limite definido':`${Math.max(0,m.limit-m.all.length)} disponíveis`,Camera],['Custo mensal previsto',eur(m.cost),'Base + planos das câmaras ativas',Euro],['Venda mensal prevista',m.missing?'Por completar':eur(m.revenue),m.missing?`${m.missing} câmaras sem plano ou preço`:'Antes de descontos e cobranças',Wallet],['Margem bruta prevista',m.missing?'—':eur(m.profit),m.missing?'Define todos os preços':m.margin===null?'Sem receita prevista':`${m.margin.toFixed(1)}% da venda`,TrendingUp]].map(([label,value,hint,I])=>{const Icon=I as typeof Camera;return <div className="metric" key={String(label)}><div><span>{String(label)}</span><Icon size={19}/></div><strong className="money-value">{String(value)}</strong><small>{String(hint)}</small></div>})}</section>
 <div className="two-col"><section className="panel form-panel"><div className="flex justify-between items-center"><h2>Licença e capacidade</h2><span className={`pill ${licenseStatus(r).tone}`}>{licenseStatus(r).label}</span></div><div className="wallet-track"><div style={{width:`${m.limit?Math.min(100,m.all.length/m.limit*100):0}%`}}/></div><p>{m.all.length} câmaras cadastradas, incluindo suspensas. {m.active.length} ativas para a previsão mensal.</p><div className="storage-row">Modalidade<span>{r.licenseMode==='trial'?'Trial':'Contrato'}</span></div><div className="storage-row">Validade<span>{r.validUntil?new Date(r.validUntil+'T12:00:00').toLocaleDateString('pt-PT'):'Sem data definida'}</span></div><div className="storage-row">Mensalidade base<span>{eur(m.base)}</span></div>{!readOnly&&<Button variant="outline" onClick={()=>onEdit(r.id)}>Gerir carteira e validade</Button>}</section><section className="panel form-panel"><h2>Como calculamos a previsão</h2><p><strong>Custo:</strong> mensalidade base do revendedor + preço de custo dos planos das câmaras ativas.</p><p><strong>Venda:</strong> preço específico da câmara, quando definido; caso contrário, preço de revenda do respetivo plano.</p><p><strong>Margem bruta:</strong> venda − custo. Não inclui impostos, tráfego adicional, processamento ou outras despesas.</p><div className="info-box">Projeção de um mês pago completo, mesmo durante o trial. Não há cobranças automáticas. Câmaras, clientes e instalações suspensos não entram na previsão variável; a mensalidade base mantém-se.</div></section></div>
 <section className="panel activity"><div className="panel-title"><div><h2>Tabela de revenda</h2><p>O custo é definido por ti. Cada revendedor terá o seu próprio preço de venda.</p></div>{!readOnly&&<div className="flex gap-2"><Button variant="outline" disabled={!dirty||saving} onClick={()=>{setDraft({});setDirty(false)}}>Descartar</Button><Button disabled={!dirty||saving} onClick={()=>void persist()}><Save size={16}/>{saving?'A guardar…':'Guardar preços'}</Button></div>}</div>{data.cameraPlans.length?<Table><TableHeader><TableRow><TableHead>Plano por câmara</TableHead><TableHead>Custo / mês</TableHead><TableHead>Venda / mês</TableHead><TableHead>Margem unitária</TableHead></TableRow></TableHeader><TableBody>{data.cameraPlans.map(p=>{const value=priceValue(p.id);const price=value===''?null:Number(value);return <TableRow key={p.id}><TableCell><strong>{p.name}</strong><small className="cell-detail">{p.retention} dias · {p.maxResolution} · {p.monthlyGB} GB/mês{p.status==='paused'?' · Suspenso':''}</small></TableCell><TableCell>{eur(p.price)}</TableCell><TableCell>{readOnly?price===null?'Por definir':eur(price):<Input aria-label={`Preço de venda ${p.name}`} type="number" min="0" max="100000" step="0.01" value={value} placeholder="Por definir" onChange={e=>{setDraft({...draft,[p.id]:e.target.value});setDirty(true)}}/>}</TableCell><TableCell>{price===null?'—':<span className={price<p.price?'negative':''}>{eur(price-p.price)}{price>0?` (${((price-p.price)/price*100).toFixed(1)}%)`:''}</span>}</TableCell></TableRow>})}</TableBody></Table>:<div className="empty"><p>Cria primeiro os planos por câmara.</p></div>}<p className="table-note">A margem unitária não deduz a mensalidade base. Deixar um preço vazio significa «por definir»; zero significa oferta gratuita. Alterar a tabela não modifica preços específicos definidos nas câmaras.</p></section>
 </>}</>
}
