'use client';
import {useState} from 'react';
import {Bell,CalendarClock,Search,ArrowUpRight} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {notices,renewUntil,licenseCategory,todayLisbon} from '@/lib/operations';import {licenseStatus,commercialSummary} from '@/lib/commercial';import type {Records,Reseller} from '@/lib/model';
export default function OperationsPanel({page,data,save,saving,onOpen}:{page:string;data:Records;save:(d:Records)=>Promise<boolean>;saving:boolean;onOpen:(id:string,target:string)=>void}){
 const [filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[selected,setSelected]=useState<Reseller|null>(null),[months,setMonths]=useState('1'),[formError,setFormError]=useState('');const today=todayLisbon();const items=notices(data,today);const renewal=selected?renewUntil(selected.licenseMode==='trial'?'':selected.validUntil,Number(months),today):'';
 async function renew(){if(!selected)return;const next={...selected,licenseMode:'paid' as const,validUntil:renewal};if(await save({...data,resellers:data.resellers.map(r=>r.id===next.id?next:r)}))setSelected(null);else setFormError('Não foi possível renovar. Verifica a mensagem apresentada e os limites da carteira.');}
 return <><section className="metrics">{(page==='Alertas'?[['Alertas urgentes',items.filter(x=>x.level==='urgent').length],['Atenção',items.filter(x=>x.level==='warning').length],['Informação',items.filter(x=>x.level==='info').length],['Revendedores',data.resellers.length]]:[['Ativas',data.resellers.filter(r=>licenseCategory(r,today)==='active').length],['A expirar',data.resellers.filter(r=>licenseCategory(r,today)==='soon').length],['Expiradas',data.resellers.filter(r=>licenseCategory(r,today)==='expired').length],['Suspensas',data.resellers.filter(r=>r.status==='paused').length]]).map(([label,n])=><div className="metric" key={label}><div>{label}</div><strong>{n}</strong><small>Atualizado ao abrir esta vista</small></div>)}</section><section className="panel"><div className="panel-title"><h2>{page==='Alertas'?'O que precisa de atenção':'Licenças dos revendedores'}</h2><span className="pill">{today}</span></div><div className="table-tools"><div className="search-field"><Search size={16}/><Input aria-label="Pesquisar revendedor" placeholder="Pesquisar revendedor…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filtrar alertas ou licenças"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos</SelectItem>{(page==='Alertas'?[['urgent','Urgentes'],['warning','Atenção'],['info','Informação']]:[['active','Ativas'],['soon','A expirar'],['expired','Expiradas'],['paused','Suspensas']]).map(([v,l])=><SelectItem value={v} key={v}>{l}</SelectItem>)}</SelectContent></Select></div>
 {page==='Alertas'?<>{items.filter(n=>(filter==='all'||n.level===filter)&&n.name.toLowerCase().includes(search.toLowerCase())).map(n=><div className="notice-row" key={n.id}><Bell size={20} className={n.level==='urgent'?'negative':''}/><div><strong>{n.title}</strong><p>{n.name} · {n.detail}</p></div><Button variant="outline" onClick={()=>onOpen(n.resellerId,n.target)}>Resolver <ArrowUpRight size={15}/></Button></div>)}{!items.some(n=>(filter==='all'||n.level===filter)&&n.name.toLowerCase().includes(search.toLowerCase()))&&<div className="empty"><Bell className="mx-auto mb-4"/><h2>Sem alertas nesta seleção</h2></div>}<p className="table-note">Avisos dentro da aplicação, calculados a partir dos cadastros. Não representam alertas de câmaras nem enviam emails ou notificações push.</p></>:<><Table><TableHeader><TableRow><TableHead>Revendedor</TableHead><TableHead>Modalidade</TableHead><TableHead>Validade</TableHead><TableHead>Estado</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody>{data.resellers.filter(r=>(filter==='all'||licenseCategory(r,today)===filter)&&r.name.toLowerCase().includes(search.toLowerCase())).map(r=><TableRow key={r.id}><TableCell>{r.name}</TableCell><TableCell>{r.licenseMode==='trial'?'Trial':'Contrato'}</TableCell><TableCell>{r.validUntil||'Por definir'}</TableCell><TableCell><span className={`pill ${licenseStatus(r,today).tone}`}>{licenseStatus(r,today).label}</span></TableCell><TableCell><div className="flex gap-2 flex-wrap"><Button size="sm" variant="outline" disabled={saving} onClick={()=>{setSelected(r);setMonths('1');setFormError('')}}><CalendarClock size={15}/>{r.licenseMode==='trial'?'Converter em contrato':'Renovar'}</Button><Button size="sm" variant="ghost" onClick={()=>onOpen(r.id,'Ficha')}>Ver ficha</Button></div></TableCell></TableRow>)}</TableBody></Table>{!data.resellers.length&&<div className="empty"><p>Cria primeiro um revendedor.</p></div>}<p className="table-note">Renovar altera a validade do cadastro, sem efetuar cobranças. A suspensão mantém-se até ser alterada na ficha. O bloqueio de gravação só será integrado quando houver serviço de vídeo.</p></>}
 </section><Dialog open={!!selected} onOpenChange={o=>{if(!o&&!saving)setSelected(null)}}><DialogContent><DialogHeader><DialogTitle>{selected?.licenseMode==='trial'?'Converter trial em contrato':'Renovar licença'}</DialogTitle><DialogDescription>{selected?.name}. Confirma a nova validade antes de guardar.</DialogDescription></DialogHeader><Label>Período</Label><Select value={months} onValueChange={setMonths}><SelectTrigger aria-label="Período de renovação"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="1">1 mês</SelectItem><SelectItem value="3">3 meses</SelectItem><SelectItem value="12">12 meses</SelectItem></SelectContent></Select><div className="info-box">Validade atual: {selected?.validUntil||'Por definir'}<br/><strong>Nova validade: {renewal}</strong><p>{selected?.licenseMode==='trial'?'O contrato começa hoje. Aplica-se a carteira contratada, que pode diferir do limite de trial.':'Se ainda estiver válida, acrescentamos o período à data atual de fim; caso contrário, contamos a partir de hoje.'}</p></div>{formError&&<p role="alert" className="form-error">{formError}</p>}<Button disabled={saving} onClick={()=>void renew()}>{saving?'A guardar…':'Confirmar nova validade'}</Button></DialogContent></Dialog></>
}
export function ResellerDetails({data,id,onEdit,onCommercial}:{data:Records;id:string;onEdit:()=>void;onCommercial:()=>void}){const r=data.resellers.find(x=>x.id===id);if(!r)return <div className="empty">Revendedor não encontrado.</div>;const clients=data.clients.filter(c=>c.resellerId===id);const locations=data.locations.filter(l=>clients.some(c=>c.id===l.clientId));const m=commercialSummary(data,r);const eur=(v:number)=>v.toLocaleString('pt-PT',{style:'currency',currency:'EUR'});return <><div className="detail-brand">{r.logoId&&<img src={`/api/logo?id=${r.logoId}`} alt={`Logótipo ${r.name}`}/>}<div><h2>{r.brand}</h2><p>{r.email} {r.phone&&`· ${r.phone}`}</p></div><span className={`pill ${licenseStatus(r).tone}`}>{licenseStatus(r).label}</span></div><div className="detail-stats"><div><strong>{clients.length}</strong>Clientes</div><div><strong>{locations.length}</strong>Instalações</div><div><strong>{m.all.length} / {m.limit??'—'}</strong>Câmaras</div></div><div className="info-box">Custo mensal previsto: {eur(m.cost)} · Venda: {m.missing?'Por completar':eur(m.revenue)} · Margem bruta: {m.missing?'Por completar':eur(m.profit)}<br/>Valores sem IVA, para um mês pago completo. Não representam faturação realizada.</div><h3 className="font-semibold mt-4">Clientes e instalações</h3>{clients.length?clients.map(c=><div className="client-detail" key={c.id}><strong>{c.name}</strong><small>{c.email} · {c.status==='active'?'Ativo':'Suspenso'}</small>{locations.filter(l=>l.clientId===c.id).map(l=><p key={l.id}>{l.name} · {data.cameras.filter(x=>x.locationId===l.id).length} câmaras</p>)}</div>):<p>Ainda não há clientes associados.</p>}<div className="flex gap-3 mt-5"><Button onClick={onEdit}>Editar revendedor</Button><Button variant="outline" onClick={onCommercial}>Carteira e preços</Button></div></>}
